### ISSUE TITLE
Search engine breaks after second search if filters are included

### ISSUE THREAD

**Issue by alesanchezr** [refresh-miami/refresh-miami#33]
**Describe the bug**
Website returns 404 when search and filtering the search at the same time.

**To Reproduce**
1. Go to news
2. Search for any keyword
3. Pick a filter from the list
4. Search the keyword again

**Expected behavior**
List of news results
- After the user selects an option under "type" "topic" and "industry" the website displays 404 message.

![image](https://user-images.githubusercontent.com/80592328/124048170-b573c980-d9e3-11eb-8541-4ac82aab7d50.png)

**Comment by mariaderchi** [comment]
I left this comment on a similar bug reported - David, should we just hide the filter box for now (type, topic, industry) if that is an easy thing to do? I want to make sure our news articles are properly tagged before we allow filtering so that the filters pull good results. We could leave the 'Categories' filter. Let me know your thoughts.

**Comment by mariaderchi** [comment]
Disregard - I see that the filters have been removed. Perhaps I was on a cached page before. We can close this ticket.
