### ISSUE TITLE
As a public user the section under "Profile" and "View" should show centered

### ISSUE THREAD

**Issue by YodaFace** [refresh-miami/refresh-miami#35]
## User Story:
As a public user the section under "Profile" and "View" should show centered, currently it shows to the right of the page.  This is currently how the page looks:
![Screen Shot 2021-07-02 at 7 17 05 PM](https://user-images.githubusercontent.com/13352282/124337937-c733a900-db6a-11eb-9340-7af1a37f261c.png)

## Acceptance Criteria:
This section should be centered:
![Screen Shot 2021-07-02 at 7 04 43 PM](https://user-images.githubusercontent.com/13352282/124337923-b125e880-db6a-11eb-906c-7bb7568b5a8d.png)

**Comment by dimensionmedia** [comment]
This is not going to work. The area (see screenshot) that is empty should contain some sort of "about me" text. Centering the area wouldn't work (and also isn't really possible because this is a two column template).

Perhaps this ticket should be turned into more of a "sample text to put here so this area doesn't look so empty"?

![Screen Shot 2021-07-12 at 9 05 28 AM](https://user-images.githubusercontent.com/721134/125292283-4f931600-e2f0-11eb-9980-cb27d332ebb5.png)

Here's what I mean when the about text is present:

![Screen Shot 2021-07-12 at 9 05 58 AM](https://user-images.githubusercontent.com/721134/125292355-6174b900-e2f0-11eb-9413-cc1b0c20d5aa.png)
