### ISSUE TITLE
As a public user, tabs in the timeline should be not restricted.

### ISSUE THREAD

**Issue by allenstfort23** [refresh-miami/refresh-miami#36]
## User Story:
```
As a public user, I should be able to see what I liked, connections, etc ... and should not be restricted. 
```
## Acceptance Criteria:

Elaborate more on the story for specific expected behaviors, for example:
- Go to the down drop next to the user's name.
- Drop down to the timeline tab
- Click on any tab beside personal.
- 
![Screen Shot 2021-07-02 at 8 21 59 PM](https://user-images.githubusercontent.com/50781372/124337939-2ac1d480-db73-11eb-90c8-cfe170c65ed1.png)

**Comment by dimensionmedia** [comment]
![Screen Shot 2021-07-12 at 9 01 28 AM](https://user-images.githubusercontent.com/721134/125291767-c11e9480-e2ef-11eb-83fa-b8d3c304fcc2.png)

1. I was only able to see this as a non-admin viewing another profile following the instructions above (please note).
2. I deactivated the"Restrict Content For BuddyPress" plugin and reactivated it.
3. I am now able to view the same pages (logged in as the non-admin test user) without the restriction. See screenshot.

I'm not sure if turning on/off the plugin did anything. @allenstfort23 if you can retest and if you get same results PLEASE note the USERNAME you are using when you are logged in and the specific urls if you are seeing the messages. Thank you.

**Comment by mariaderchi** [comment]
I just tested this out using a non-admin account and I'm still getting the restricted message - https://www.loom.com/share/988f2fc936d94035804c432c180a72e3

**Comment by dimensionmedia** [comment]
I deactivated a plugin (see #40) and not getting access issues. I'm wondering why the plugin was installed in the first place, what we were trying to restrict.

**Comment by mariaderchi** [comment]
The plugin was originally installed to serve as our membership plugin so that we could gate certain content based on membership level. Not sure if we ended up using it for that - let me know if it rings a bell.

**Comment by mariaderchi** [comment]
FYI on some additional issues, one that may have come about because we disabled Restrict Content Pro - https://www.loom.com/share/e0b4fe123ae7428dbdcc32694da998bf

**Comment by dimensionmedia** [comment]
- Update links to post a job on this page @mariaderchi : https://mymiami.tech/wp-admin/post.php?post=182&action=edit
- I reactivated the BuddyPress Restrict Content Pro plugin, which allows you to view your membership level, past invoices, etc. - everything that we had before (although now likely restored some other issues). Since things were reviewed and approved before, i assume restoring this requires no further work on memberships in profiles.
- Back to the oringial issue on this ticket. I dug into the plugin (sorry Maria, you'll see this on the billable hours lol) and forced it to allow access to profile pages so that as Maria (the test user) looks at Maria (the user with the more updated profile) it works and no "restricted message". See screenshot.

So to be clear we resolved the oringial ticket issue and by turning back on a plugin I turned off restored what was missing from yesterday/day before.

![Screen Shot 2021-07-27 at 9 32 55 AM](https://user-images.githubusercontent.com/721134/127162991-03b32c5d-e41b-47ab-908e-49ebaa153c04.png)

**Comment by mariaderchi** [comment]
Thanks @dimensionmedia! I did some updated testing. Please watch this video - https://www.loom.com/share/f1812f19772047dbbc0d540cdaf38fa2.

**Comment by dimensionmedia** [comment]
Forums links updated.

Video on posting job and membership levels, etc. : https://www.loom.com/share/eee2d38b697b4a969f5041b8faef7f8c

See above in my eariler update about the wp-admin link to update the post a job links to point to right site.

Have a good rest of the day!

**Comment by mariaderchi** [comment]
Hi David - I can update the link but I don't know what the correct URL is to reach the page where you can actually post a job. Can you share that link with me?

**Comment by dimensionmedia** [comment]
Same link, just replace the domain name. ‘Refresh.miami’ becomes ‘mymiami.tech'
