### ISSUE TITLE
News Filters still appearing and different categories on different pages

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#46]
**Describe the bug**
While we removed the News filters on the News homepage, they are still appearing on some pages. Also on the main News page, only two News categories are listed but on an individual article page, if you scroll down you will find a bunch of categories. 

Check out this Loom video - https://www.loom.com/share/67b1502d29c346bea34d5692af14b5a3

**Comment by dimensionmedia** [comment]
Old search removed from category pages:
https://mymiami.tech/category/community-news/

Regarding the categories on this page, those are generated by WordPress widgets.
https://mymiami.tech/wp-admin/widgets.php

I believe it's the "blog sidebar". Designer never said what to do with these pages, and nobody has commented on them until now. We can remove the category widget easily.

The categories like Startup News appear because we check off (I believe) an option on pages like this:
https://mymiami.tech/wp-admin/term.php?taxonomy=category&tag_ID=1386&post_type=post&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dcategory

So you can control the categories that appear on that top area. Hope this makes sense!

**Comment by mariaderchi** [comment]
Thanks David! I went ahead and removed the 'Categories' widget from the blog sidebar. Closing this ticket now.
