### ISSUE TITLE
Cannot reset my password

### ISSUE THREAD

**Issue by alesanchezr** [refresh-miami/refresh-miami#70]
![Screen Shot 2021-09-22 at 11 16 45 PM](https://user-images.githubusercontent.com/426452/134449959-ab112482-7972-42cb-a4ee-e6de07f291e9.png)

**Comment by dimensionmedia** [comment]
I'm cc'ing @brianbreslin on this one since I don't know why this would be happening. We are getting emails from Gravity Forms when users are activated, so email is technically working on the site.

https://refreshmiami.com/wp-admin/options-general.php?page=sendgrid-settings.php

@brianbreslin can we maybe double check SendGrid? When i deeactivate SendGrid the error message doesn't happen.


![Screen Shot 2021-09-23 at 4 25 18 AM](https://user-images.githubusercontent.com/721134/134476049-a529af37-eb9d-46de-8f84-949355fa1015.png)

**Comment by brianbreslin** [comment]
There was something from sendgrid of needing to upgrade the account as it was on a 100 per month email account. I can investigate it this morning   
  
  
  
    
  

  
  
>

**Comment by mariaderchi** [comment]
Fixed! Thanks everyone!
